### Autenticación
POST http://localhost/api-flight/auth
Content-Type: application/json

{
	"correo": "admin@gmail.com",
	"contrasena": "Mi_contraseña.1234"
}

### Crear usuario
POST http://localhost/api-flight/usuarios
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjU3MDAwNTYsIm5iZiI6MTc2NTcwMDA1NiwiZXhwIjoxNzY1NzAzNjU2LCJkYXRhIjp7ImlkIjoxLCJyb2wiOiJhZG1pbiJ9fQ.ZMdEarYe7rYQj9z6INdqjpvILhmvrA2tA03cISQlHEM
Content-Type: application/json

{
	"nombre": "Elías Peña",
	"telefono": "04129428521",
	"correo": "eliaspena@gmail.com",
	"contrasena": "Mi_contraseña.123"
}

### Todos los usuarios
GET http://localhost/api-flight/usuarios
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjU3MDAwNTYsIm5iZiI6MTc2NTcwMDA1NiwiZXhwIjoxNzY1NzAzNjU2LCJkYXRhIjp7ImlkIjoxLCJyb2wiOiJhZG1pbiJ9fQ.ZMdEarYe7rYQj9z6INdqjpvILhmvrA2tA03cISQlHEM

### Un solo usuario
GET http://localhost/api-flight/usuarios/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjU3MDAwNTYsIm5iZiI6MTc2NTcwMDA1NiwiZXhwIjoxNzY1NzAzNjU2LCJkYXRhIjp7ImlkIjoxLCJyb2wiOiJhZG1pbiJ9fQ.ZMdEarYe7rYQj9z6INdqjpvILhmvrA2tA03cISQlHEM

### Un solo usuario
GET http://localhost/api-flight/usuarios/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjU3MDAwNTYsIm5iZiI6MTc2NTcwMDA1NiwiZXhwIjoxNzY1NzAzNjU2LCJkYXRhIjp7ImlkIjoxLCJyb2wiOiJhZG1pbiJ9fQ.ZMdEarYe7rYQj9z6INdqjpvILhmvrA2tA03cISQlHEM

### Usuario no encontrado
GET http://localhost/api-flight/usuarios/0
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjU3MDAwNTYsIm5iZiI6MTc2NTcwMDA1NiwiZXhwIjoxNzY1NzAzNjU2LCJkYXRhIjp7ImlkIjoxLCJyb2wiOiJhZG1pbiJ9fQ.ZMdEarYe7rYQj9z6INdqjpvILhmvrA2tA03cISQlHEM

### Editar usuario
PUT http://localhost/api-flight/usuarios/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjU3MDAwNTYsIm5iZiI6MTc2NTcwMDA1NiwiZXhwIjoxNzY1NzAzNjU2LCJkYXRhIjp7ImlkIjoxLCJyb2wiOiJhZG1pbiJ9fQ.ZMdEarYe7rYQj9z6INdqjpvILhmvrA2tA03cISQlHEM
Content-Type: application/json

{
	"nombre": "Elías Peña",
	"telefono": "04248056940",
	"correo": "eliaspena@gmail.com",
	"contrasena": "Mi_contraseña.123"
}

### Editar usuario
PUT http://localhost/api-flight/usuarios/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjU3MDAwNTYsIm5iZiI6MTc2NTcwMDA1NiwiZXhwIjoxNzY1NzAzNjU2LCJkYXRhIjp7ImlkIjoxLCJyb2wiOiJhZG1pbiJ9fQ.ZMdEarYe7rYQj9z6INdqjpvILhmvrA2tA03cISQlHEM
Content-Type: application/json

{
	"nombre": "Mi nombre modificado otra vez"
}

### Editar usuario
PUT http://localhost/api-flight/usuarios/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjU3MDAwNTYsIm5iZiI6MTc2NTcwMDA1NiwiZXhwIjoxNzY1NzAzNjU2LCJkYXRhIjp7ImlkIjoxLCJyb2wiOiJhZG1pbiJ9fQ.ZMdEarYe7rYQj9z6INdqjpvILhmvrA2tA03cISQlHEM
Content-Type: application/json

{
	"telefono": "04241234567"
}

### Editar usuario
PUT http://localhost/api-flight/usuarios/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjU3MDAwNTYsIm5iZiI6MTc2NTcwMDA1NiwiZXhwIjoxNzY1NzAzNjU2LCJkYXRhIjp7ImlkIjoxLCJyb2wiOiJhZG1pbiJ9fQ.ZMdEarYe7rYQj9z6INdqjpvILhmvrA2tA03cISQlHEM
Content-Type: application/json

{
	"correo": "admin@gmail.com"
}

### Editar usuario
PUT http://localhost/api-flight/usuarios/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjU3MDAwNTYsIm5iZiI6MTc2NTcwMDA1NiwiZXhwIjoxNzY1NzAzNjU2LCJkYXRhIjp7ImlkIjoxLCJyb2wiOiJhZG1pbiJ9fQ.ZMdEarYe7rYQj9z6INdqjpvILhmvrA2tA03cISQlHEM
Content-Type: application/json

{
	"contrasena": "Mi_contraseña.1234"
}

### Editar usuario (sin parámetros)
PUT http://localhost/api-flight/usuarios/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjU3MDAwNTYsIm5iZiI6MTc2NTcwMDA1NiwiZXhwIjoxNzY1NzAzNjU2LCJkYXRhIjp7ImlkIjoxLCJyb2wiOiJhZG1pbiJ9fQ.ZMdEarYe7rYQj9z6INdqjpvILhmvrA2tA03cISQlHEM

### Editar usuario no encontrado
PUT http://localhost/api-flight/usuarios/0
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjU3MDAwNTYsIm5iZiI6MTc2NTcwMDA1NiwiZXhwIjoxNzY1NzAzNjU2LCJkYXRhIjp7ImlkIjoxLCJyb2wiOiJhZG1pbiJ9fQ.ZMdEarYe7rYQj9z6INdqjpvILhmvrA2tA03cISQlHEM
Content-Type: application/json

{
	"nombre": "Mi nombre modificado",
	"telefono": "04241234567",
	"correo": "mi_otro_correo@gmail.com"
}

### Borrar usuario
DELETE http://localhost/api-flight/usuarios/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjU3MDAwNTYsIm5iZiI6MTc2NTcwMDA1NiwiZXhwIjoxNzY1NzAzNjU2LCJkYXRhIjp7ImlkIjoxLCJyb2wiOiJhZG1pbiJ9fQ.ZMdEarYe7rYQj9z6INdqjpvILhmvrA2tA03cISQlHEM

### Borrar usuario no encontrado
DELETE http://localhost/api-flight/usuarios/0
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3NjU3MDAwNTYsIm5iZiI6MTc2NTcwMDA1NiwiZXhwIjoxNzY1NzAzNjU2LCJkYXRhIjp7ImlkIjoxLCJyb2wiOiJhZG1pbiJ9fQ.ZMdEarYe7rYQj9z6INdqjpvILhmvrA2tA03cISQlHEM

