
GET http://localhost/api-flight/usuarios
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NjU2NDA4NDUsImRhdGEiOjF9.WV8oeCFFVnSGuN_J_x_CRZfeNSBotMlZ86koIL9Q2w8

###

GET http://localhost/api-flight/usuarios
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NjU2NDA4NDUsImRhdGEiOjF9.WV8oeCFFVnSGuN_J_x_CRZfeNSBotMlZ86koIL9Q2w8
Content-Type: application/json

{
	"id": 1
}

###

POST http://localhost/api-flight/usuarios
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NjU2NDA4NDUsImRhdGEiOjF9.WV8oeCFFVnSGuN_J_x_CRZfeNSBotMlZ86koIL9Q2w8
Content-Type: application/json

{
	"nombre": "Elías Peña",
	"telefono": "04129428521",
	"correo": "eliasspt@gmail.com",
	"contrasena": "maofcr12"
}

###

PUT http://localhost/api-flight/usuarios
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NjU2NDA4NDUsImRhdGEiOjF9.WV8oeCFFVnSGuN_J_x_CRZfeNSBotMlZ86koIL9Q2w8
Content-Type: application/json

{
	"id": 1,
	"nombre": "Elías Santiago Peña Torrenegra",
	"telefono": "04248056940",
	"correo": "eliasspt.android@gmail.com"
}

###

DELETE http://localhost/api-flight/usuarios
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NjU2NDA4NDUsImRhdGEiOjF9.WV8oeCFFVnSGuN_J_x_CRZfeNSBotMlZ86koIL9Q2w8
Content-Type: application/json

{
	"id": 2
}

###

POST http://localhost/api-flight/auth
Content-Type: application/json

{
	"correo": "eliasspt@gmail.com",
	"contrasena": "maofcr12"
}